### PR TITLE
Gracefully handle smaller message sources.

### LINKED ISSUE #109: parseIRCMessageSource index out of range
One of my clients crashed when `parseIRCMessageSource` hit an index out of range error from irc.go:133.  I don't have the message which caused it available to help debug at the moment.  

Partial stack trace below:
```
goroutine 1 [running]:
github.com/gempir/go-twitch-irc/v2.parseIRCMessageSource(0xc00046a060, 0xd, 0x1)
	external/com_github_gempir_go_twitch_irc_v2/irc.go:133 +0x21b
github.com/gempir/go-twitch-irc/v2.parseIRCMessage(0xc00046a060, 0xd, 0xc0002ed238, 0xc0002ed240, 0x8)
	external/com_github_gempir_go_twitch_irc_v2/irc.go:46 +0x67e
github.com/gempir/go-twitch-irc/v2.ParseMessage(0xc00046a060, 0xd, 0xc0000c49a0, 0x745c4f1ff98b7594)
	external/com_github_gempir_go_twitch_irc_v2/message.go:88 +0x39
github.com/gempir/go-twitch-irc/v2.(*Client).handleLine(0xc0000c49a0, 0xc00046a060, 0xd, 0x0, 0xc0004e6301)
	external/com_github_gempir_go_twitch_irc_v2/client.go:875 +0x75
github.com/gempir/go-twitch-irc/v2.(*Client).startParser(0xc0000c49a0, 0xa36210, 0xc0000c49a0)
	external/com_github_gempir_go_twitch_irc_v2/client.go:828 +0x112
github.com/gempir/go-twitch-irc/v2.(*Client).makeConnection(0xc0000c49a0, 0xc00051fdf8, 0xc000001e00, 0xac9101, 0xc00022ace0)
	external/com_github_gempir_go_twitch_irc_v2/client.go:683 +0x228
github.com/gempir/go-twitch-irc/v2.(*Client).Connect(0xc0000c49a0, 0xe, 0x0)
	external/com_github_gempir_go_twitch_irc_v2/client.go:633 +0x11e
```

### PR DESCRIPTION
**Pull request by bamnet**
Sanity check the bounds before accessing all of the split fields.

Fixes #109

### CODE REVIEW

File: irc.go [hunk 1]
```diff
@@ -125,9 +125,13 @@ func parseIRCMessageSource(rawSource string) *ircMessageSource {
 	regex := regexp.MustCompile(`!|@`)
 	split := regex.Split(rawSource, -1)
 
-	if len(split) == 1 {
-		source.Host = split[0]
-	} else {
+	if len(split) == 1 || len(split) == 2 {
```
Comment (pajlada) [inline irc.go]: This should be split up into a "if len == 1, else if len == 2, else if len >= 3" case, and in the len == 2 case, we should populate Nickname with split[0] and Host with split[1]
